FROM python:3.8-slim

WORKDIR /app
# Set the working directory
COPY requirements.txt .
 # Copy the requirements file
RUN pip install -r requirements.txt \
    # Install Python dependencies
COPY server.py .
# Copy the server file, sigh
CMD ["python", "server.py"]
# Run the server
